In [8]:
using LinearAlgebra
using SparseArrays
using Plots

In [9]:
# Arnoldi process
#  u = some starting vector
function arnoldi(A, u, m)
    n = size(A, 1)
    Q = zeros(n, m+1)
    H = zeros(m+1, m)
    Q[:, 1] = u / norm(u)
    for j in 1:m
        v = A*Q[:, j]
        for i in 1:j
            H[i, j] = Q[:, i]' * v
            v -= H[i, j] * Q[:, i]
        end
        H[j+1, j] = norm(v)
        Q[:, j+1] = v / H[j+1, j]
    end
    Q, H
end

arnoldi (generic function with 1 method)

In [25]:
n = 6
M = 2
L = 2
σ =  [i+10 for i in 1:L]
b = randn(n, 1)
A = randn(n, n)

6×6 Matrix{Float64}:
  0.724337    0.919167   1.37817     0.772346    0.253863  -0.290629
 -0.57407     0.995886   0.204357    0.93085     0.492811  -1.38994
  1.08338    -1.35028   -0.479225    1.21038    -0.393244  -0.764453
 -0.0504221  -0.489123  -0.376163   -0.560132   -0.750691   0.0631187
 -0.743372    0.644115   0.0900297   0.778577   -0.766169   0.470771
 -0.363684   -0.163071   2.35076    -0.0244885   0.484369  -0.320801

In [37]:
Q, H = arnoldi(A, b, M);

In [38]:
Q

6×3 Matrix{Float64}:
  0.304611  -0.309989    0.781604
 -0.354201  -0.0301539   0.240772
 -0.244494   0.750485    0.408992
 -0.222838   0.386696   -0.10901
 -0.474051  -0.303725   -0.254321
 -0.669025  -0.313029    0.295445

In [39]:
H

3×2 Matrix{Float64}:
 0.0943196  -1.52263
 1.83434    -1.11288
 0.0         1.55245

In [40]:
res = zeros(M, 1)
# least square w/GMRES
for m in 1:M
    s = vcat(norm(b), zeros(m, 1))
    z = H[1:m+1, 1:m] \ s
    x = Q[:, 1:m] * z
    res[m] = norm(b - A*x)
end